name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and run testing
      run: |
        docker build . -f ./client/Dockerfile.dev -t 102205:react-test
        docker run 102205:react-test npm test -- --coverage

    - name: Build multi docker images
      run: |
        docker build -t 102205/multi-client ./client
        docker build -t 102205/multi-nginx ./nginx
        docker build -t 102205/multi-server ./server
        docker build -t 102205/multi-worker ./worker

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
