name: Pre-deploy

on:
  pull_request:
    branches: [ "main" ]

env:
  TEST_TAG: 102205/multi-docker-client:test
  LATEST_TAG: 102205/multi-docker:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        context: ./client
        file: ./client/Dockerfile.dev
        load: true
        tags: ${{ env.TEST_TAG }}

    - name: Run test
      run: |
        docker run --rm -e CI=true ${{ env.TEST_TAG }} npm test -- --coverage
